// Code generated by MockGen. DO NOT EDIT.
// Source: dao/dao.go
//
// Generated by this command:
//
//	mockgen -source=dao/dao.go -destination=mocks/mock_dao.go
//

// Package mock_dao is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mapset "github.com/deckarep/golang-set/v2"
	dao "github.com/sashankg/hold/dao"
	gomock "go.uber.org/mock/gomock"
)

// MockDao is a mock of Dao interface.
type MockDao struct {
	ctrl     *gomock.Controller
	recorder *MockDaoMockRecorder
}

// MockDaoMockRecorder is the mock recorder for MockDao.
type MockDaoMockRecorder struct {
	mock *MockDao
}

// NewMockDao creates a new mock instance.
func NewMockDao(ctrl *gomock.Controller) *MockDao {
	mock := &MockDao{ctrl: ctrl}
	mock.recorder = &MockDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDao) EXPECT() *MockDaoMockRecorder {
	return m.recorder
}

// AddCollection mocks base method.
func (m *MockDao) AddCollection(ctx context.Context, collection *dao.Collection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCollection", ctx, collection)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCollection indicates an expected call of AddCollection.
func (mr *MockDaoMockRecorder) AddCollection(ctx, collection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCollection", reflect.TypeOf((*MockDao)(nil).AddCollection), ctx, collection)
}

// FindCollectionFieldsByCollectionId mocks base method.
func (m *MockDao) FindCollectionFieldsByCollectionId(ctx context.Context, fieldMap map[int]mapset.Set[string]) (map[int]*dao.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCollectionFieldsByCollectionId", ctx, fieldMap)
	ret0, _ := ret[0].(map[int]*dao.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCollectionFieldsByCollectionId indicates an expected call of FindCollectionFieldsByCollectionId.
func (mr *MockDaoMockRecorder) FindCollectionFieldsByCollectionId(ctx, fieldMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCollectionFieldsByCollectionId", reflect.TypeOf((*MockDao)(nil).FindCollectionFieldsByCollectionId), ctx, fieldMap)
}

// FindCollectionFieldsBySpec mocks base method.
func (m *MockDao) FindCollectionFieldsBySpec(ctx context.Context, fieldMap map[dao.CollectionSpec]mapset.Set[string]) (map[dao.CollectionSpec]*dao.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCollectionFieldsBySpec", ctx, fieldMap)
	ret0, _ := ret[0].(map[dao.CollectionSpec]*dao.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCollectionFieldsBySpec indicates an expected call of FindCollectionFieldsBySpec.
func (mr *MockDaoMockRecorder) FindCollectionFieldsBySpec(ctx, fieldMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCollectionFieldsBySpec", reflect.TypeOf((*MockDao)(nil).FindCollectionFieldsBySpec), ctx, fieldMap)
}

// FindCollections mocks base method.
func (m *MockDao) FindCollections(ctx context.Context, names []string) (map[int]*dao.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCollections", ctx, names)
	ret0, _ := ret[0].(map[int]*dao.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCollections indicates an expected call of FindCollections.
func (mr *MockDaoMockRecorder) FindCollections(ctx, names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCollections", reflect.TypeOf((*MockDao)(nil).FindCollections), ctx, names)
}

// GetRecord mocks base method.
func (m *MockDao) GetRecord(ctx context.Context, id int, selection []dao.Selection, collectionId int, collectionMap map[int]*dao.Collection) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecord", ctx, id, selection, collectionId, collectionMap)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecord indicates an expected call of GetRecord.
func (mr *MockDaoMockRecorder) GetRecord(ctx, id, selection, collectionId, collectionMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecord", reflect.TypeOf((*MockDao)(nil).GetRecord), ctx, id, selection, collectionId, collectionMap)
}
